name: cxr-triage
channels:
  - conda-forge
  - nvidia
  - anaconda
  - pytorch
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.2.25
  - cuda-cccl=13.1.115
  - cuda-cccl_win-64=13.1.115
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.1.115
  - cuda-opencl-dev=13.1.115
  - cuda-profiler-api=13.1.115
  - cuda-runtime=12.4.1
  - cuda-version=13.1
  - filelock=3.24.3
  - fmt=12.1.0
  - fsspec=2026.2.0
  - giflib=5.2.2
  - icu=78.2
  - jinja2=3.1.6
  - khronos-opencl-icd-loader=2025.07.22
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20260107.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.4.1.81
  - libcurand-dev=10.4.1.81
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.25
  - libexpat=2.7.4
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=13.1.115
  - libnvfatbin-dev=13.1.115
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.55
  - libprotobuf=6.33.5
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libtorch=2.10.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=22.1.0
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mpmath=1.4.0
  - networkx=3.6.1
  - numpy=2.4.2
  - opencl-headers=2025.07.22
  - openjpeg=2.5.4
  - openssl=3.6.1
  - optree=0.19.0
  - pillow=12.1.1
  - pip=26.0.1
  - pthread-stubs=0.4
  - pybind11=3.0.2
  - pybind11-abi=11
  - pybind11-global=3.0.2
  - python=3.14.3
  - python_abi=3.14
  - pytorch=2.10.0
  - pytorch-cuda=12.4
  - setuptools=82.0.0
  - sleef=3.9.0
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - torchvision=0.25.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - aiofiles==24.1.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - argcomplete==3.6.3
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.2.0
      - attrs==25.4.0
      - audioop-lts==0.2.2
      - babel==2.18.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - boto3==1.42.58
      - botocore==1.42.58
      - brotli==1.2.0
      - cachetools==7.0.1
      - certifi==2026.2.25
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cross-web==0.4.1
      - cryptography==46.0.5
      - cycler==0.12.1
      - dacite==1.9.2
      - debugpy==1.8.20
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - dill==0.4.1
      - dnspython==2.8.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.133.1
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - fiftyone==1.13.2
      - fiftyone-brain==0.21.5
      - fiftyone-db==1.4.1
      - fonttools==4.61.1
      - fqdn==1.5.1
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glob2==0.7
      - gradio==6.7.0
      - gradio-client==2.2.0
      - graphql-core==3.2.7
      - groovy==0.1.2
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.3.1
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.5.0
      - humanize==4.15.0
      - hypercorn==0.18.0
      - hyperframe==6.1.0
      - idna==3.11
      - imageio==2.37.2
      - inflate64==1.0.4
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jmespath==1.1.0
      - joblib==1.5.3
      - json5==0.13.0
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kaggle==2.0.0
      - kagglesdk==0.1.15
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.2.0
      - mongoengine==0.29.1
      - motor==3.6.1
      - multivolumefile==0.2.3
      - narwhals==2.17.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.5.4
      - notebook-shim==0.2.4
      - opencv-python==4.13.0.92
      - opencv-python-headless==4.13.0.92
      - orjson==3.11.7
      - packaging==26.0
      - pandas==3.0.1
      - pandocfilters==1.5.1
      - paramiko==3.5.1
      - parso==0.8.6
      - platformdirs==4.9.2
      - plotly==6.5.2
      - polars==1.38.1
      - polars-runtime-32==1.38.1
      - pprintpp==0.4.0
      - priority==2.0.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.5
      - psutil==7.2.2
      - pure-eval==0.2.3
      - py7zr==1.1.0
      - pybcj==1.0.7
      - pycparser==3.0
      - pycryptodomex==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydash==8.0.6
      - pydicom==3.0.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pymongo==4.9.2
      - pynacl==1.6.2
      - pyparsing==3.3.2
      - pyppmd==1.3.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-multipart==0.0.22
      - python-slugify==8.0.4
      - pytz==2025.2
      - pywinpty==3.0.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rarfile==4.2
      - referencing==0.37.0
      - regex==2026.2.19
      - requests==2.32.5
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.3.3
      - rpds-py==0.30.0
      - rtree==1.4.1
      - s3transfer==0.16.0
      - safehttpx==0.1.7
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.17.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==2.1.0
      - sentry-sdk==2.53.0
      - shellingham==1.5.4
      - simsimd==6.5.13
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - soupsieve==2.8.3
      - sse-starlette==0.10.3
      - sseclient-py==1.9.0
      - stack-data==0.6.3
      - starlette==0.52.1
      - strawberry-graphql==0.291.3
      - stringzilla==4.6.0
      - tabulate==0.9.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2026.2.24
      - tinycss2==1.4.0
      - tomlkit==0.13.3
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - typer==0.24.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - ultralytics==8.4.18
      - ultralytics-thop==2.0.18
      - universal-analytics-python3==1.1.1
      - uri-template==1.3.0
      - urllib3==2.6.3
      - uvicorn==0.41.0
      - voxel51-eta==0.15.3
      - wandb==0.25.0
      - wcwidth==0.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - wrapt==2.1.1
      - wsproto==1.3.2
      - xmltodict==1.0.4
prefix: C:\ProgramData\miniconda3\envs\cxr-triage
